AWSTemplateFormatVersion: "2010-09-09"
Description: "This is a CFN role"
Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowAssumeRole
            Effect: Allow
            Principal:
              Service: "cloudformation.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
Outputs:
  IamRole:
    Value: !GetAtt IamRole.Arn

# aws cloudformation create-stack --stack-name cfniamrole  --capabilities CAPABILITY_IAM  --template-body file://4-create-service-role.yaml --profile ${MY_PROFILE} --region eu-central-1
# IAM_ROLE_ARN=$(aws cloudformation describe-stacks --profile ${MY_PROFILE} --region eu-central-1 --stack-name cfniamrole --query "Stacks[0].Outputs[?OutputKey=='IamRole'].OutputValue" --output text)
# aws cloudformation create-stack --profile ${MY_PROFILE} --stack-name mybucket --template-body file://1-first-bucket.yaml --region eu-central-1 --role-arn $IAM_ROLE_ARN
